name: CI
on:
  pull_request:
    branches: [master]
  schedule: [cron: "12 */24 * * *"]

jobs:
  build-and-simulate:
    name: Build and Simulate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Git Sumbodule Update
        run: |
          git submodule update --remote --recursive
      - name: Check out Scapy code
        uses: actions/checkout@v2
        with:
          repository: secdev/scapy
          path: ./scapy
      - name: Prepare Environment
        run : |
          sudo apt update
          sudo apt install -y protobuf-compiler python3.10 net-tools librdmacm-dev ibverbs-utils rdmacm-utils perftest
          python3 -m pip install grpcio grpcio-tools scapy black
          pip install --upgrade protobuf
          cargo install --version 2.25.0 protobuf-codegen
          cargo install grpcio-compiler
          ./rdma-env-setup/scripts/setup.sh
      - name: Compile
        run: |
          # Python format check
          black --check `find ./src -name "*.py"`
          ./build_proto.sh
          cargo build
          docker build -t grpc-python3 ./test
      - name: Run
        run: |
          ./test/run.sh
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
